/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author DarkSouls
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menu Principal");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbcompras = new javax.swing.JButton();
        jbventas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menucrear = new javax.swing.JMenuItem();
        menuusers = new javax.swing.JMenuItem();
        menusalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuproducto = new javax.swing.JMenuItem();
        menuinventario = new javax.swing.JMenuItem();
        menuproveedor = new javax.swing.JMenuItem();
        menulisprovee = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        reporventa = new javax.swing.JMenuItem();
        reporcompra = new javax.swing.JMenuItem();
        reporinv = new javax.swing.JMenuItem();
        Otros = new javax.swing.JMenu();
        menuporusu = new javax.swing.JMenuItem();
        menureporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 350));

        jbcompras.setBackground(new java.awt.Color(0, 0, 0));
        jbcompras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbcompras.setForeground(new java.awt.Color(255, 255, 255));
        jbcompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32-compra.png"))); // NOI18N
        jbcompras.setText("Compras");

        jbventas.setBackground(new java.awt.Color(0, 0, 0));
        jbventas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbventas.setForeground(new java.awt.Color(255, 255, 255));
        jbventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32-producto.png"))); // NOI18N
        jbventas.setText("Ventas");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JUANCARS.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbcompras, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jbcompras)
                .addGap(52, 52, 52)
                .addComponent(jbventas)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbcompras, jbventas});

        jMenu1.setText("Nuevo");

        menucrear.setText("Crear Usuario");
        jMenu1.add(menucrear);

        menuusers.setText("Usuarios");
        jMenu1.add(menuusers);

        menusalir.setText("Salir");
        jMenu1.add(menusalir);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Opciones");

        menuproducto.setText("Producto nuevo");
        jMenu3.add(menuproducto);

        menuinventario.setText("Auditar inventario");
        jMenu3.add(menuinventario);

        menuproveedor.setText("Incluir proveedores");
        jMenu3.add(menuproveedor);

        menulisprovee.setText("Lista de proveedores");
        jMenu3.add(menulisprovee);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Reportes");

        reporventa.setText("Ventas");
        jMenu2.add(reporventa);

        reporcompra.setText("Compras");
        jMenu2.add(reporcompra);

        reporinv.setText("Inventario");
        jMenu2.add(reporinv);

        Otros.setText("Otros");

        menuporusu.setText("Ventas por usuario");
        Otros.add(menuporusu);

        menureporte.setText("Ventas por fecha");
        Otros.add(menureporte);

        jMenu2.add(Otros);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Otros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton jbcompras;
    public javax.swing.JButton jbventas;
    public javax.swing.JMenuItem menucrear;
    public javax.swing.JMenuItem menuinventario;
    public javax.swing.JMenuItem menulisprovee;
    public javax.swing.JMenuItem menuporusu;
    public javax.swing.JMenuItem menuproducto;
    public javax.swing.JMenuItem menuproveedor;
    public javax.swing.JMenuItem menureporte;
    public javax.swing.JMenuItem menusalir;
    public javax.swing.JMenuItem menuusers;
    public javax.swing.JMenuItem reporcompra;
    public javax.swing.JMenuItem reporinv;
    public javax.swing.JMenuItem reporventa;
    // End of variables declaration//GEN-END:variables
}
