/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Knight
 */
public class Registrousu extends javax.swing.JFrame {

    /**
     * Creates new form Registrousu
     */
    public Registrousu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbpregunta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtresp = new javax.swing.JTextField();
        txtnomusu = new javax.swing.JTextField();
        btregistrar = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cedemple = new javax.swing.JTextField();
        txtnomemp = new javax.swing.JTextField();
        txtapeemple = new javax.swing.JTextField();
        txtdirecemple = new javax.swing.JTextField();
        btmodificar = new javax.swing.JButton();
        btsalir2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        cbtpusuario = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jctpdoc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(528, 338));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 480));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registro de usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 25, -1, -1));

        jLabel2.setText("nombre de usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 120, -1));

        jLabel3.setText("contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 120, -1));

        cbpregunta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primera Mascota", "Compleaños Madre", "Lugar de nacimiento", "otra" }));
        jPanel1.add(cbpregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 130, -1));

        jLabel4.setText("respuesta secreta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 130, -1));

        jLabel5.setText("pregunta secreta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 130, -1));
        jPanel1.add(txtresp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 130, -1));
        jPanel1.add(txtnomusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 130, -1));

        btregistrar.setBackground(new java.awt.Color(0, 0, 0));
        btregistrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btregistrar.setForeground(new java.awt.Color(255, 255, 255));
        btregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32-guardar.png"))); // NOI18N
        btregistrar.setText("Registrar");
        jPanel1.add(btregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btsalir.setBackground(new java.awt.Color(0, 0, 0));
        btsalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btsalir.setForeground(new java.awt.Color(255, 255, 255));
        btsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32-salir.png"))); // NOI18N
        btsalir.setText("Salir");
        jPanel1.add(btsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 113, 89, -1));

        jLabel7.setText("Apellido");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 156, 89, -1));

        jLabel8.setText("Direccion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 194, 89, -1));

        jLabel9.setText("Cedula");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 75, 50, -1));
        jPanel1.add(cedemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 72, 130, -1));
        jPanel1.add(txtnomemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 110, 130, -1));
        jPanel1.add(txtapeemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 153, 130, -1));
        jPanel1.add(txtdirecemple, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 191, 130, -1));

        btmodificar.setBackground(new java.awt.Color(0, 0, 0));
        btmodificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32-actualizar.png"))); // NOI18N
        btmodificar.setText("Modificar");
        jPanel1.add(btmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        btsalir2.setBackground(new java.awt.Color(0, 0, 0));
        btsalir2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btsalir2.setForeground(new java.awt.Color(255, 255, 255));
        btsalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x32-salir.png"))); // NOI18N
        btsalir2.setText("Salir");
        jPanel1.add(btsalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel10.setText("*");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 10, -1));

        jLabel11.setText("*");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 10, 20));

        jLabel12.setText("* Campos obligatorios");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel13.setText("*");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 30, -1));

        jLabel14.setText("*");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));
        jPanel1.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 130, -1));

        jLabel15.setText("Tipo de usuario");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        cbtpusuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un usuario", "Administrador", "Facturador" }));
        jPanel1.add(cbtpusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 130, -1));

        jLabel16.setText("*");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 10, -1));

        jLabel17.setText("*");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 10, -1));

        jctpdoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "J", "V", "E" }));
        jPanel1.add(jctpdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrousu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrousu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrousu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrousu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrousu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btmodificar;
    public javax.swing.JButton btregistrar;
    public javax.swing.JButton btsalir;
    public javax.swing.JButton btsalir2;
    public javax.swing.JComboBox<String> cbpregunta;
    public javax.swing.JComboBox<String> cbtpusuario;
    public javax.swing.JTextField cedemple;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> jctpdoc;
    public javax.swing.JTextField txtapeemple;
    public javax.swing.JPasswordField txtcontraseña;
    public javax.swing.JTextField txtdirecemple;
    public javax.swing.JTextField txtnomemp;
    public javax.swing.JTextField txtnomusu;
    public javax.swing.JTextField txtresp;
    // End of variables declaration//GEN-END:variables
}
